import { z } from 'zod';

// =============================================================================
// Character Status
// =============================================================================

export const CHARACTER_STATUS = {
  DRAFT: 'draft',
  APPROVED: 'approved',
} as const;

export type CharacterStatus = (typeof CHARACTER_STATUS)[keyof typeof CHARACTER_STATUS];

export const characterStatusSchema = z.enum([
  CHARACTER_STATUS.DRAFT,
  CHARACTER_STATUS.APPROVED,
]);

// =============================================================================
// Character Schema & Types
// =============================================================================

/**
 * Portrait option generated by AI
 */
export const portraitOptionSchema = z.object({
  id: z.string(),
  url: z.url(),
  prompt: z.string().optional(),
  seed: z.number().optional(),
  generatedAt: z.iso.datetime(),
});

export type PortraitOption = z.infer<typeof portraitOptionSchema>;

/**
 * Character entity for AI Video Generator
 * First-class entity as per BRIEF 4.2
 */
export const characterSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  name: z.string().min(1),
  description: z.string().optional(),
  /** Selected master portrait URL for consistency */
  masterPortraitUrl: z.url().optional(),
  /** All generated portrait options (typically 4) */
  portraitOptions: z.array(portraitOptionSchema).optional(),
  /** Character status - must be approved before use in scenes */
  status: characterStatusSchema,
  /** Version for artifact tracking */
  version: z.number().default(1),
  // BaseEntity fields
  created: z.string(),
  updated: z.string(),
  isActive: z.boolean(),
  isDeleted: z.boolean(),
});

export type Character = z.infer<typeof characterSchema>;

// =============================================================================
// Character Input Schemas
// =============================================================================

export const createCharacterSchema = z.object({
  projectId: z.string(),
  name: z.string().min(1, 'Character name is required'),
  description: z.string().optional(),
});

export type CreateCharacterInput = z.infer<typeof createCharacterSchema>;

export const updateCharacterSchema = z.object({
  name: z.string().min(1).optional(),
  description: z.string().optional(),
  masterPortraitUrl: z.url().optional(),
  status: characterStatusSchema.optional(),
});

export type UpdateCharacterInput = z.infer<typeof updateCharacterSchema>;

// =============================================================================
// AI Character Extraction
// =============================================================================

/**
 * AI-extracted character suggestion from story content
 */
export interface CharacterSuggestion {
  name: string;
  description: string;
  /** Confidence score from AI (0-1) */
  confidence?: number;
}

export interface ExtractCharactersResponse {
  characters: CharacterSuggestion[];
  /** Raw AI response for debugging */
  rawResponse?: string;
}

// =============================================================================
// Character List Params
// =============================================================================

export interface CharacterListParams {
  projectId: string;
  status?: CharacterStatus;
}
