import { z } from 'zod';
import { type BaseListParams } from '@superapp/shared-types';

// =============================================================================
// Character Status
// =============================================================================

export const CHARACTER_STATUS = {
  DRAFT: 'draft',
  APPROVED: 'approved',
} as const;

export type CharacterStatus = (typeof CHARACTER_STATUS)[keyof typeof CHARACTER_STATUS];

export const characterStatusSchema = z.enum([
  CHARACTER_STATUS.DRAFT,
  CHARACTER_STATUS.APPROVED,
]);

// =============================================================================
// Character Schema & Types
// =============================================================================

/**
 * Portrait option generated by AI
 */
export const portraitOptionSchema = z.object({
  url: z.string(),
  prompt: z.string().optional(),
  isSelected: z.boolean().optional(),
});

export type PortraitOption = z.infer<typeof portraitOptionSchema>;

/**
 * Character entity for AI Video Generator
 */
export const characterSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  name: z.string(),
  description: z.string().optional(),
  visualTraits: z.string().optional(),
  masterPortraitUrl: z.string().optional(),
  portraitOptions: z.array(portraitOptionSchema).optional(),
  status: characterStatusSchema,
  version: z.number().default(1),
  userId: z.string(),
  // BaseEntity fields
  created: z.string(),
  updated: z.string(),
  isActive: z.boolean(),
  isDeleted: z.boolean(),
});

export type Character = z.infer<typeof characterSchema>;

// =============================================================================
// Character Input Schemas
// =============================================================================

export const createCharacterSchema = z.object({
  projectId: z.string(),
  name: z.string().min(1, 'Character name is required'),
  description: z.string().optional(),
  visualTraits: z.string().optional(),
});

export type CreateCharacterInput = z.infer<typeof createCharacterSchema>;

export const updateCharacterSchema = z.object({
  name: z.string().min(1).optional(),
  description: z.string().optional(),
  visualTraits: z.string().optional(),
  masterPortraitUrl: z.string().optional(),
  portraitOptions: z.array(portraitOptionSchema).optional(),
  status: characterStatusSchema.optional(),
  version: z.number().optional(),
  isActive: z.boolean().optional(),
  isDeleted: z.boolean().optional(),
});

export type UpdateCharacterInput = z.infer<typeof updateCharacterSchema>;

// =============================================================================
// Character List Params
// =============================================================================

export interface CharacterListParams extends BaseListParams {
  projectId: string;
  status?: CharacterStatus;
}

// =============================================================================
// AI Extraction Types
// =============================================================================

export interface CharacterSuggestion {
  name: string;
  description: string;
  visualTraits: string;
}

export interface ExtractCharactersResponse {
  characters: CharacterSuggestion[];
}
