import { 
  Folder, 
  Tag, 
  ShoppingBag, 
  Smartphone, 
  Coffee, 
  Utensils, 
  Car, 
  Home, 
  Laptop, 
  Headphones, 
  Watch, 
  Gift, 
  Book, 
  Activity, 
  Heart, 
  Star, 
  Package, 
  Truck, 
  Wrench, 
  Zap, 
  Music, 
  Camera, 
  Gamepad2, 
  Shirt,
  type LucideIcon
} from 'lucide-react';

export type CategoryIcon = LucideIcon;

// Map of available icons for categories
export const CATEGORY_ICONS: Record<string, CategoryIcon> = {
  folder: Folder,
  tag: Tag,
  shopping_bag: ShoppingBag,
  smartphone: Smartphone,
  coffee: Coffee,
  utensils: Utensils,
  car: Car,
  home: Home,
  laptop: Laptop,
  headphones: Headphones,
  watch: Watch,
  gift: Gift,
  book: Book,
  activity: Activity,
  heart: Heart,
  star: Star,
  package: Package,
  truck: Truck,
  wrench: Wrench,
  zap: Zap,
  music: Music,
  camera: Camera,
  gamepad: Gamepad2,
  shirt: Shirt,
};
